In [1]:
import pandas 

In [4]:
db=pandas.read_csv("marks.csv")

In [5]:
 type(db)

pandas.core.frame.DataFrame

In [6]:
 db

name  hrs  marks
0  vimal    7     70
1  rahul    5     50
2   eric    8     80
3  harry    2     20

In [7]:
db['marks']

0    70
1    50
2    80
3    20
Name: marks, dtype: int64

In [8]:
y=db['marks']

In [9]:
y

0    70
1    50
2    80
3    20
Name: marks, dtype: int64

In [13]:
x=db['hrs']

In [14]:
x

0    7
1    5
2    8
3    2
Name: hrs, dtype: int64

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
mind=LinearRegression

In [26]:
x.reshape(4,1)

AttributeError: 'Series' object has no attribute 'reshape'

In [22]:
y

0    70
1    50
2    80
3    20
Name: marks, dtype: int64

In [27]:
x.values

array([7, 5, 8, 2], dtype=int64)

In [28]:
x.reshape(4,1)

AttributeError: 'Series' object has no attribute 'reshape'

In [23]:
mind.fit(x,y)

TypeError: fit() missing 1 required positional argument: 'y'

In [29]:
x

0    7
1    5
2    8
3    2
Name: hrs, dtype: int64

In [30]:
type(x)

pandas.core.series.Series

In [33]:
x=x.values

In [34]:
x.reshape(4,1)

array([[7],
       [5],
       [8],
       [2]], dtype=int64)

In [35]:
x.shape

(4,)

In [36]:
x

array([7, 5, 8, 2], dtype=int64)

In [37]:
x = x.values

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [38]:
x =x.reshape(4,1)

In [39]:
x.shape

(4, 1)

In [40]:
x

array([[7],
       [5],
       [8],
       [2]], dtype=int64)

In [41]:
mind.fit(x, y)

TypeError: fit() missing 1 required positional argument: 'y'

In [42]:
y

0    70
1    50
2    80
3    20
Name: marks, dtype: int64

In [43]:
x

array([[7],
       [5],
       [8],
       [2]], dtype=int64)

In [44]:
from sklearn.linear_model import LinearRegression

In [50]:
mind= LinearRegression()

In [51]:
mind.fit(x,y)

LinearRegression()

In [52]:
x

array([[7],
       [5],
       [8],
       [2]], dtype=int64)

In [56]:
y

0    70
1    50
2    80
3    20
Name: marks, dtype: int64

mind.predict(9)

In [55]:
mind.predict(9)

ValueError: Expected 2D array, got scalar array instead:
array=9.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [57]:
x = x.reshape(4,1)

In [58]:
x.shape

(4, 1)

In [59]:
mind.fit(x,y)

LinearRegression()

In [60]:
mind.predict(7)

ValueError: Expected 2D array, got scalar array instead:
array=7.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [61]:
mind.predict([[6]])

array([60.])

In [62]:
mind.coef_

array([10.])

In [63]:
import joblib

In [64]:
joblib.dump(mind,'marks.pk1')

['marks.pk1']